export const Names = [
    "Olivia",
    "Noah",
    "Emma",
    "Liam",
    "Amelia",
    "Oliver",
    "Sophia",
    "Elijah",
    "Charlotte",
    "Mateo",
    "Ava",
    "Lucas",
    "Isabella",
    "Levi",
    "Mia",
    "Leo",
    "Luna",
    "Ezra",
    "Evelyn",
    "Luca",
    "Gianna",
    "Asher",
    "Lily",
    "James",
    "Aria",
    "Ethan",
    "Aurora",
    "Sebastian",
    "Ellie",
    "Henry",
    "Harper",
    "Muhammad",
    "Mila",
    "Hudson",
    "Sofia",
    "Maverick",
    "Camila",
    "Benjamin",
    "Layla",
    "Theo",
    "Nova",
    "Kai",
    "Eliana",
    "Jackson",
    "Ella",
    "Michael",
    "Violet",
    "Daniel",
    "Hazel",
    "Aiden",
    "Willow",
    "Gabriel",
    "Chloe",
    "Josiah",
    "Ivy",
    "Mason",
    "Scarlett",
    "Jack",
    "Penelope",
    "Elias",
    "Eleanor",
    "Grayson",
    "Elena",
    "Alexander",
    "Avery",
    "Luke",
    "Nora",
    "Julian",
    "Abigail",
    "Jayden",
    "Emily",
    "David",
    "Maya",
    "Logan",
    "Isla",
    "Theodore",
    "Delilah",
    "Wyatt",
    "Naomi",
    "Carter",
    "Elizabeth",
    "Samuel",
    "Grace",
    "Owen",
    "Zoey",
    "William",
    "Emilia",
    "Waylon",
    "Riley",
    "Ezekiel",
    "Zoe",
    "Miles",
    "Paisley",
    "Matthew",
    "Athena",
    "Isaiah",
    "Leilani",
    "Jacob",
    "Madison",
    "Santiago",
    "Victoria",
    "Caleb",
    "Ayla",
    "John",
    "Stella",
    "Joseph",
    "Lucy",
    "Thomas",
    "Kinsley",
    "Adam",
    "Iris",
    "Amir",
    "Gabriella",
    "Isaac",
    "Lainey",
    "Nolan",
    "Aaliyah",
    "Nathan",
    "Serenity",
    "Zion",
    "Addison",
    "Jeremiah",
    "Alice",
    "Lincoln",
    "Bella",
    "Adrian",
    "Sadie",
    "Anthony",
    "Sophie",
    "Cooper",
    "Amara",
    "Eli",
    "Autumn",
    "Micah",
    "Summer",
    "Cameron",
    "Emery",
    "Enzo",
    "Everly",
    "Ryan",
    "Valentina",
    "Roman",
    "Hannah",
    "Rowan",
    "Brooklyn",
    "Xavier",
    "Madelyn",
    "Jaxon",
    "Natalie",
    "Wesley",
    "Leah",
    "Weston",
    "Maria",
    "Andrew",
    "Savannah",
    "Joshua",
    "Amira",
    "Silas",
    "Aubrey",
    "Colton",
    "Jade",
    "Charlie",
    "Jasmine",
    "Parker",
    "Eden",
    "Christopher",
    "Skylar",
    "Greyson",
    "Josie",
    "Luka",
    "Clara",
    "Atlas",
    "Adeline",
    "Dominic",
    "Elliana",
    "Christian",
    "Millie",
    "Myles",
    "Lillian",
    "Brooks",
    "Melody",
    "Kayden",
    "Sarah",
    "Austin",
    "Eva",
    "Aaron",
    "Ruby",
    "Omar",
    "Freya",
    "Amari",
    "Lyla",
    "Axel",
    "Adalynn",
    "Beau",
    "Liliana",
    "Jasper",
    "Daisy",
    "Landon",
    "Nevaeh",
    "Max",
];

export const Locations = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Côte d'Ivoire",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini (fmr. \"Swaziland\")",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];

export const Products = [
    "Umay Under Desk Treadmill",
    "Earth Rated Dog Poop Bags",
    "J Jimoo Mulberry Silk Pillowcase",
    "Bedsure Sherpa Fleece Throw Blanket",
    "Laneige Lip Sleeping Mask",
    "DEWALT 20V Max Cordless Drill / Driver Kit",
    "Apple AirPods (2nd Generation)",
    "DearHouse 2 Pack Fall Garland Maple Leaf",
    "Carhartt Men's Knit Camo Beanie",
    "Pampers Sensitive Water Based Hypoallergenic and Unscented Baby Wipes",
    "Chuckit! Ultra Ball Dog Toy",
    "Benebone Wishbone Durable Dog Chew Toy for Aggressive Chewers",
    "PlayStation DuelSense Wireless Controller",
    "Stanley Quencher H2.0",
    "Mighty Patch",
    "Fourth Wing by Rebecca Yarros",
    "Blink Outdoor (3rd Gen)",
    "Occer Compact Binoculars",
    "Hanes Men's Ecosmart Hoodie",
    "Apple AirTag",
    "TERRO T300B Liquid Ant Killer",
    "Purina Fancy Feast Gravy Lovers",
    "Pokemon Cards",
    "Hasbro Gaming Perfection Game",
    "Xbox Gift Card",
];